language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: kegan+isogon@keganmyers.com
  api_key:
    secure: UvcDFzK4QXWh0rWbgv4hfTWj/D9P90vGq8zz/YUCqC8HY1c/eztcUesDWFeIggmBfRcIaocJe0VBRQIMlPFnANC+Rgk6x4tmW4AUFeqqXCGofG2yUie/uJIVJ7+Tgdba7H+enrOGSbhNSZoMZKAN+4vdgNo0CkjX79D1VuvtitxZ5gGz4D9osP2MPUEqrkBpvG4k+nW/YnS07YQ6S8B2O2Opxj8GgTQH3XIzIK++H+N5iERnl/ahYsxhpP/MDd/NN1KJiPkmh7X1NpVJH1gjsD398JCTKfZmzj+HlLUaRn4mIvgLViXyymT0gJPs/1mA/kyOdquD56Py3dPBuFMhvqbNdz3eEO1F0jUGKo8a9EbqQ+EFieqVKLOeNIpbwSAS3Y540XUkhSwxbV7FfNpFefDa1aagxbbCSuaRYfJChFX49HWkj3xcs7Sinle5BFv/NuC/+R8Dh0kL7I0opsq5ZdDpH4oplIw5PDXwgJNhBlnKG9BsLWiLRNYPRD+bccEdnRSb21zbKsSbFf0x8p80R+jSIMkgE8WVbroNoTbKQCv0YdVqKrgb75epldFYtq1wSecoJwhhZHeiuM3Cqr+5ISQiDfq5T4+7MzQU6IfvFUIEJWbt10X1L1Ink4gFDF4ICbrXKBiAHwXI1j5SEUR1ftBMbylYM/EFl1e0ohUJYVg=
  skip_cleanup: true
  on:
    tags: true
    repo: isogon/inject
